---
name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@2.0.4
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
